<?php
$title = $this->translate('Edit album');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'edit', 'id' => $this->id,)));
$form->get('submit')->setValue($this->translate('Edit'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();