<?php
$title = $this->translate('My albums');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action' => 'add')); ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th><?= $this->translate('Title') ?></th>
        <th><?= $this->translate('Artist') ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title); ?></td>
            <td><?php echo $this->escapeHtml($album->artist); ?></td>
            <td>
                <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id)); ?>"><?= $this->translate('Edit') ?></a>
                <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id)); ?>"><?= $this->translate('Delete') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>